vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        category:
            uri_prefix: /Images/Mariages
            upload_destination: '%kernel.project_dir%/public/Images/Mariages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true